name: Release
on:
  push:
    branches:
      - main
      - develop
      - NET8

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
      # QEMU
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      # Buildx
      - name: Setup Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v3
      # Docker login
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Login, build & publish docker image
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          provenance: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/octothorp.gateway:${{ steps.gitversion.outputs.NuGetVersionV2 }}
            ghcr.io/${{ github.repository_owner }}/octothorp.gateway:${{ steps.gitversion.outputs.Major }}${{ steps.gitversion.outputs.PreReleaseLabelWithDash }}
            ghcr.io/${{ github.repository_owner }}/octothorp.gateway:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}${{ steps.gitversion.outputs.PreReleaseLabelWithDash }}
          build-args: RELEASE_VERSION=${{ steps.gitversion.outputs.NuGetVersionV2 }}